version: "3"
services:
  database:
    container_name: database
    image: postgres:12.3
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "mydatabaseuser"
      POSTGRES_PASSWORD: "mypassword"
    networks:
      - project
      - storage
    expose:
      - "5432"
  backend:
    container_name: backend
    image: bartleby2718/mod_wsgi-docker-simple
    volumes:
      - ./backend:/app
    networks:
      - project
      - storage
    depends_on:
      - database
    ports:
      - "8000:8000"
    command: bash setup.sh
  frontend:
    container_name: frontend
    image: bartleby2718/react-scripts
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    networks:
      - project
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: sh /app/setup.sh
networks:
  project:
  storage:
