version: "3"
services:
  backend:
    container_name: backend
    image: bartleby2718/mod_wsgi-docker-simple
    volumes:
      - ./backend:/app
    networks:
      - project
    ports:
      - "8000:8000"
    command: bash setup.sh
  frontend:
    container_name: frontend
    image: node:alpine
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    networks:
      - project
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: sh /app/setup.sh
networks:
  project:
